Repository kris-hansen/comanda, pull requests merged in 2025-02, with the labels that each got.

#35 Scraping Use Case Updates
  examples/web-scraping/scrape-example.yaml
  utils/models/deepseek.go
  utils/models/ollama.go
  utils/models/provider.go
  utils/processor/dsl.go
  utils/scraper/scraper.go
Labels: enhancement, Review effort [1-5]: 3, Possible security concern

#36 Update Input Validation in Tests
  examples/examples_test.go
Labels: enhancement, Review effort [1-5]: 2

#37 SSE streaming
  cmd/process.go
  docs/openapi.yaml
  utils/config/env.go
  utils/config/server.go
  utils/processor/dsl.go
  utils/processor/dsl_test.go
  utils/processor/input_handler.go
  utils/processor/input_test.go
  utils/processor/model_test.go
  utils/processor/output_handler.go
  utils/processor/output_handler_test.go
  utils/processor/progress.go
  utils/server/auth.go
  utils/server/bulk_operations_test.go
  utils/server/env_handlers_test.go
  utils/server/file_backup_test.go
  utils/server/file_download_test.go
  utils/server/file_handlers.go
  utils/server/file_handlers_test.go
  utils/server/file_upload_test.go
  utils/server/handlers.go
  utils/server/handlers_test.go
  utils/server/provider_handlers_test.go
  utils/server/server.go
  utils/server/types.go
Labels: enhancement, Review effort [1-5]: 3

#39 feat: latest anthropic models
  cmd/configure.go
  examples/model-examples/claude-3-7-example.yaml
  utils/models/anthropic.go
Labels: enhancement, Review effort [1-5]: 2
